spring.application.name=dishsg

# Stripe
spring.config.import=optional:classpath:application-local.properties,optional:file:./application-local.properties
stripe.secret-key=${STRIPE_SECRET_KEY}


spring.datasource.url=jdbc:postgresql://localhost:5443/postgres
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.rabbitmq.host=localhost
spring.rabbitmq.username=user
spring.rabbitmq.password=password
spring.rabbitmq.port=5672

# Keycloak JWT resource server (realm: kdg)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/kdg


# see routing keys, exchanges, confirms/returns
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG
logging.level.org.springframework.amqp.rabbit.core.RabbitTemplate=TRACE
# spring modulith event externalization logs
logging.level.org.springframework.modulith=DEBUG
logging.level.org.springframework.modulith.events=DEBUG

